---
- name: Validate sshd configuration
  ansible.builtin.command:
    cmd: /usr/sbin/sshd -t
  register: sshd_syntax_check
  changed_when: false
  listen:
    - "reload sshd"
    - "restart sshd"
  notify: Restart ssh service

- name: Restart ssh service
  ansible.builtin.service:
    name: "{{ sshd_service_name }}"
    state: restarted
  listen: "Restart ssh service"
